### ISSUE TITLE
IWorld -> GenView

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1133]
A followup of ancient #448. #1098 gives me the idea that interfaces can be named `view`, and this interface is a view for potentially async world generation view, hence `GenView` should suffice. Please vote.

**Comment by i509VCB** [comment]
Did we want to use the `Gen` abbreviation or `Generation`

On the case of IWorld currently, it is right where the split between regular `World`, Client and Server worlds and ChunkRegion (very commonly used in World gen) begins.

Whether we should use `World` or `View` is another question as IWorld starts to define some worldly functions such as the existence of state scheduling, difficulties and chunk managers. 

The mentions of IWorld's use in world gen is a good argument for why Gen/GenerationView could work, however I feel a name like IntermediaryWorld could work but that also doesn't compensate for the possible world gen context this would be used within.

GenerationView or IntermediaryWorld are my two choices but I would like to see some more arguments before a firm decision.

**Comment by valoeghese** [comment]
iapprove

**Comment by Juuxel** [comment]
I like @i509VCB's `GenerationView`.

**Comment by jaskarth** [comment]
I vote for GenerationView as well.

**Comment by i509VCB** [comment]
Would like to put some steam back into the discussion here.

The listed options I've seen mentioned in this issue  so far:

GenView
GenerationView
IntermediaryWorld
GeneratableWorld (basically #448 with new naming standard)

My opinions on the above:
GenView is nice and short but Gen does not very explicit with the abbrivation's meaning (General, Generation, Genji?)

GenerationView and GeneratableWorld both fall in the same category of being much more explicit than GenView

IntermediaryWorld is a compromise as not all world types are actually generatable (Client worlds). 
Also due to the fact this class is an interface, the intermediary portion of the name says this represents a sort of "partial definition" for a world or a worldly functions.

Some other ideas:
ProtoWorld (inspired by the sponge api name and based on the Greek word proto, which in this context would be used to mean basic or prototype). 

PrimativeWorld (assuming we use primative in the sense of a simplistic object), issue I see is the connotation with socital definition of primitive which makes no sense with a type of world

**Comment by YanisBft** [comment]
Closed by #1350
