### ISSUE TITLE
Conventions.md file is obsolete

### ISSUE THREAD

**Issue by YanisBft** [asiekierka/MinecraftPOMF#1209]
The major issue here is that the file doesn't take into account Mojang official mappings. It should indicate the legal issues about these mappings, and the fact that we shouldn't look at them before we make a pull request.

Additionally, as seen with #1189 , the conventions file should make it clear that we preferably use hardcoded identifiers instead of default translations for objects like blocks, items, entities, biomes, etc, when naming classes.

**Comment by Runemoro** [comment]
> the fact that we shouldn't look at them before we make a pull request.

That's not really a naming convention. It also doesn't mention MCP. Both Mojmap and MCP are covered [in the readme](https://github.com/FabricMC/yarn#contributing) though:

> Please remember that copying and pasting mappings from alternate projects under more restrictive licenses (such as MCP) is **completely forbidden** without explicit permission from the owners of said mappings. 

Maybe the readme should explicitly mention Mojang mappings (so change "such as MCP" to "such as MCP or the official Mojang mappings"). Also, it should say "taking" rather than "copying and pasting", since "copying and pasting" sounds like it only forbids taking many mappings but using a few is OK.
