### ISSUE TITLE
Naming convention for registry object constant classes.

### ISSUE THREAD

**Issue by Earthcomputer** [asiekierka/MinecraftPOMF#1673]
Before 1.16, we had classes which held a bunch of registry objects, such as `Blocks`, `Items`, `EntityTypes` and `Biomes`.
In 1.16, the way registries work got refactored, and some registries are now synchronized. This has created a bit of a mess with the naming of these classes. In particular, I am talking about the continued existence of the `Biomes` class, for which since 1.16.2-rc2 only 2 important biome objects are held, and `BuiltinBiomes`, which stores all the registry keys.

I propose a new naming convention for these classes:
- Simple plural if the registry does not use `DynamicRegistryManager`. I.e. `Blocks`, `Items`, etc stay as they are.
- `Builtin` prefix for classes that store the actual objects that go in the registry. E.g. the class currently named `Biomes` -> `BuiltinBiomes`.
- `Keys` suffix for classes storing a list of `RegistryKey`s. E.g. the class currently named `BuiltinBiomes` -> `BiomeKeys`.

The rationale behind the `Builtin` prefix being used in this way, is that it's used for the biomes which are *essential* for the game to function. By the way 

Any objections to these renames?

**Comment by shartte** [comment]
I **_fully_** agree with what is proposed here. (p.s.: I probably would like 'Ids' over 'Keys' as the suffix, but since the data type is currently named RegistryKey, it's appropriate to use the 'Keys' suffix)

I saw some back and forth between `BuiltIn` and `Builtin`. I don't know what the current preference is (and when it'll be changed again ;-)). This should be taken into account.
