### ISSUE TITLE
Why are Style#withUnderline and Style#withFont client-side only?

### ISSUE THREAD

**Issue by uTen2c** [asiekierka/MinecraftPOMF#1877]
I don't see this as just a client-side process, is there a reason for this?

**Comment by i509VCB** [comment]
This is a technicality with how the game is distributed. Proguard at build time will strip method not used in server platform, and since `withFont` is only used on client it is omitted from server.

A solution is adding a sort of style builder to fabric api so the methods can be bypassed (the backing fields exist regardless of platform)
