### ISSUE TITLE
Name local variables

### ISSUE THREAD

**Issue by Bixilon** [asiekierka/MinecraftPOMF#2362]
I sometimes look into the code and see variables like `lv` and they have no meaning at all. It'd be great if it'd be possible to name local variables. 

I know this also wold mean making changes to the tiny format, enigma, ... It's "a huge thing", but still making this issue. I also can help, but idk how exactly.

Thanks

Moritz

**Comment by haykam821** [comment]
Yarn is not planned to have local variable mappings due to the amount of work it would take to maintain it. Instead, the decompilers should have smarter local variable guessing, such as `Entity entity1 = this.getAttacker()` being changed to `Entity attacker = this.getAttacker()`.

Do note that [the Tiny V2 specification](https://github.com/FabricMC/tiny-remapper/issues/9) already has support for mapping the local variable table.

**Comment by Bixilon** [comment]
Hmm I can clearly understand it. The thing is, lines like this, can't really be guessed: `float a = 1.1f`. 

Can you tell me, how to enable it in enigma, so I can use it for "temporary lookups"?
