### ISSUE TITLE
Getter naming convention

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2408]
Since mojang has moved to java 16 where record is a stable feature, once they start using records, we will have getter methods that don't follow our `getXxx` naming style. Should we revise our style?

Afai see, jdk uses `fieldName()` as getter names for final fields (and usually they are intrinsic qualities of those objects, like `Class.descriptorString()`), and `getFieldName()` as getter names for mutable fields (or sometimes less intrinsic qualities, like `Class.getModule()`). See CallSite for example. Should we do the same?

**Comment by haykam821** [comment]
I think that we should continue to use the `get` prefix in non-record classes.

**Comment by Juuxel** [comment]
This has already been discussed in #1009 too. It might be worth moving this discussion there?

I do have one point about records specifically. Kotlin converts getters using `get`/`is` to field-like properties when you call them from Kotlin. Records are special-cased to work properly without the prefixes, but that can't be done automatically for all classes (otherwise every no-arg method would be a property). Switching to prefixless naming would cause parenthesis spam compared to the old style:

```kotlin
// get prefix
val name = Blocks.STONE.name

// no prefix
val name = Blocks.STONE.name()
```

I'm not saying that this is the only thing to consider, but it does help Kotlin modders. Also, removing the prefixes would break massive amounts of mod code regardless of language (and Kotlin/Scala users can't use `migrateMappings`).

**Comment by liach** [comment]
Will make this a vote on [haykam's proposal to keep `get` prefix](https://github.com/FabricMC/yarn/issues/2408#issuecomment-841757464). Guess we will check the result upon mojang's first addition of records.

**Comment by Player3324** [comment]
Records are immutable and aren't supposed to contain substantial logic, so it's a special case similar to builders. The get prefixes are still very useful in mixed cases where mutable and/or computation operations make it less obvious what a specific method might do.

**Comment by liach** [comment]
So will take player's reasoning for now. If people object in the future, please open a new issue for debate.
