### ISSUE TITLE
CoralFeature.generate not getting mapped in output

### ISSUE THREAD

**Issue by modmuss50** [asiekierka/MinecraftPOMF#256]
CoralFeature.generate not getting mapped in build.

yarn-18w48a-tiny:

`CLASS	btf	net/minecraft/world/gen/feature/CoralFeature	net/minecraft/class_2978`
`METHOD	btf	(Lbat;Lbqa;Ljava/util/Random;Let;Lbvu;)Z	a	method_12865	method_12865`

https://github.com/FabricMC/yarn/blob/18w49a/mappings/net/minecraft/world/gen/feature/CoralFeature.mapping#L1-L4

**Comment by liach** [comment]
Still valid for 19w40a.

**Comment by Runemoro** [comment]
This issue is also because of of bridge methods not being remapped correctly.

In 18w48a, the mapping was there, but it was for the synthetic bridge method (since it was overriding the one in `Feature`, and we had mappings for overriding methods then).

Now that we no longer have mappings for overriding methods, there's no more mapping for it, and as before the bridged method isn't being remapped.
