### ISSUE TITLE
Question: How are such mappings created?

### ISSUE THREAD

**Issue by axelrindle** [asiekierka/MinecraftPOMF#273]
Since I started with Minecraft Modding a few years ago, I've always wondered how such name mappings are created, when the Minecraft Source Code is not available and all the classes are encrypted.

So how does one know which class is responsible for what and what are the correct names?

**Comment by asiekierka** [comment]
I will be writing a decent explanation of the way the toolchain works for the wiki in a few weeks, but think of it like a very, very large crossword. You have some hints (strings, mostly), and you just fill things in as you figure out answers.

**Comment by jamierocks** [comment]
> classes are encrypted

The classes are not encrypted, that's somewhat of a joke in the Java community since that's not really feasible. However, I'm assuming you meant obfuscated, which Minecraft indeed is.

You have to understand that the names in Yarn aren't accurate to what Mojang name them, as you say - we have no way to know all of their mappings (they have released a number of resource throughout the years, so we have some idea how they map things). Yarn is merely a consortium effort, where it is a best-effort thing.

**Comment by Prospector** [comment]
it's more like Sudoku than a crossword. It's actually kinda exactly like sudoku
