### ISSUE TITLE
How do I use Yarn with Forge

### ISSUE THREAD

**Issue by BD103** [asiekierka/MinecraftPOMF#2883]
Hello! I greatly prefer Yarn mappings over the official ones and MCP. Would there be a way to use Yarn for a Minecraft Forge project?

Thanks~

**Comment by liach** [comment]
Hmm, I think forge side (namely forgegradle) might be a better place to ask about this. They do have some hook for you to provide custom mappings; if you are lucky, you might find someone who already wrote a project that allows converting tiny mappings to srg for forge to use, but most likely you need to write it yourself.

Since this is not related to yarn itself, I am going to close it, but feel free to ask more within this issue (you can still comment on closed issues).

**Comment by haykam821** [comment]
I believe that [YarnForge](https://github.com/ramidzkh/yarnforge-plugin) works for everything but class names.

**Comment by modmuss50** [comment]
I could be wrong, but I think arch loom (https://github.com/architectury/architectury-loom) allows for this as well. While it would be cool for official loom to support forge, its not worth effort it to would take us to do and then to keep it maintained.

**Comment by Juuxel** [comment]
Yeah, as one of the developers of arch loom, yarn fully works for forge using it (there are some problems with really specific `Chunk` mixins, but that's the only problem I've heard of).

**Comment by BD103** [comment]
Thank you! This was exactly what I was looking for. :D

**Comment by Adrikikicp** [comment]
arch loom is a fork of Juuxel's loom (forgified loom)
