### ISSUE TITLE
[1.20.4] SimpleInventory#stacks has been renamed to "heldStacks"

### ISSUE THREAD

**Issue by Sollace** [asiekierka/MinecraftPOMF#3750]
This doesn't look to me like it was done intentionally since the name sounds like it would be more at home in the PlayerInventory class.

![image](https://github.com/FabricMC/yarn/assets/6429283/dac10cb2-26e4-492c-bdc0-0acd333a1bf3)

**Comment by Linguardium** [comment]
also affects https://github.com/FabricMC/yarn/blob/1.20.4/mappings/net/minecraft/inventory/RecipeInputInventory.mapping

Seems to be intentional as get the getter uses getHeldStacks as terminology and states "get stacks held by inventory" in the docs

https://discord.com/channels/507304429255393322/521545796882006027/1164953714726027285

it was discussed already

**Comment by Shnupbups** [comment]
Intentional change. They are the stacks held by the inventory.
