### ISSUE TITLE
Mojang package structure

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#649]
[Here's a list of all the class names in alphabetical order (which Proguard preserves), along with guesses for package names that work with the ordering](https://gist.github.com/Runemoro/e8c45aabc8f7048d0414e42ea338d510)

I'm not saying we should copy the entire structure in yarn (I'm not saying we shouldn't either), but it may help us figure out which classes are in the wrong package, misnamed (there's lots!), and which packages need to be merged to avoid [this](https://github.com/FabricMC/yarn/issues/615) in the future.

**Comment by NeunEinser** [comment]
Few notes (omitting `net.minecraft.` in names):

- ❌  `predicate` -> `advancement.criterion`: Some predicates are at least used by loot tables as well (since 1.14). In 1.13 predicates as a subpackage of criterions would have meade sense, though.
- ❌  util.NumberRange -> advancements: What the hell is NumberRange doing in advancements? It's used in a variety of places :jangthonk:
- ✔️ `predicates.*` -> `predicates` It might make sense to not have subpackages in predicates, since it seems like what Mojang is doing and it's not that many classes anyways
- ✔️ `server.function.CommandFunction` -> `command`: It's used in `command.arguments.FunctionArgumentType` too
- ✔️ `server.command`... `.CommandOutput`, `.ServerCommandSource`, `.CommandManager`, `.CommandManager`  -> `command`: I never liked stuff that are not commands in that package. This makes sense imo, although it is debatable.
- ✔️  `util.TagHelper` -> `nbt`: It's an NBT util, so debatable. But it does make sense and we might as well adapt Mojang's structure.
- ❓  `server.dedicated.command` -> `server.command`: I think the dedicated seperation does make sense, but it might also be more convinient to have all comands in one place. Mojang probably thinks of the `dedicated` package as classes that do not belong in any other package and are only for the dedicated server. Two `commands` packages that have the same meaning at two places is probably unwanted.
  - ✔️  `server.dedicated.command` -> `server.command.dedicated`: That might be a better solution to the current structure (see also previous point), though it goes against the "everything that's dedicated only goes into `server.dedicated`" moral.
- ✔️ `command.BlockDataObject`, `command.DataCommandObject`, `server.command.DataObject`, `command.EntityDataObject` -> `server.command.data.*`: The 4 classes that would go there are just utilities for DataCommand and DataCommand itself. Makes sense imo. Noteworthy is however, that DataCommandObjects are also used by `server.command.ExecuteCommand` in `executeDataStore` and `coundPathMatches`
- ❓ Maybe `???` package starting with `server.BanEntry` could be `server.util`?
- ❓ `world.entity.???` is, going from alphabetical order, most likely `world.entity.npc`. It would make sense that way imo, especially with the new trader entity.
- ❌ `world.loot.condition` *might* be `world.loot.predicate`, but since loot tables use the naming of `condition`, I am all for sticking with the current name.

That's just a small subset of differences I picked here, but it's a subset I am fairly confident with.

**Comment by Runemoro** [comment]
> ❓ Maybe ??? package starting with server.BanEntry could be server.util?

Figured it out. It's most likely `server.player`, see the latest update to the gist.

**Comment by NeunEinser** [comment]
This seems to be only one package:
```
net.minecraft.world.level.fluid
    net/minecraft/fluid/EmptyFluid (ckw)
    net/minecraft/fluid/BaseFluid (ckx)
    net/minecraft/fluid/Fluid (cky)
    net/minecraft/fluid/FluidState (ckz)
    net/minecraft/fluid/FluidStateImpl (cla)
    net/minecraft/fluid/Fluids (clb)
    net/minecraft/fluid/LavaFluid (clc)

net.minecraft.world.level.material
    net/minecraft/block/Material (cld)
    net/minecraft/block/MaterialColor (cle)
    net/minecraft/block/piston/PistonBehavior (clf)

????????
net/minecraft/fluid/WaterFluid (clg)
```

**Comment by NeunEinser** [comment]
I did a thing based on this: https://gist.github.com/NeunEinser/737f30bbbdbb1f23ae977a34b197382e

I'm not sure if I should make a new issue for this, but it doesn't feel right to have two issues about the same thing from two different maintainers.

The idea of this is to make it easier to work with it. Like that, it is more readable by computers and if you have a good json viewer, you can just collapse everything you don't care about.

It tries to find package-info files for all packages and reports any package without a package-info.
It also includes all missing obfuscated names, which in some cases might hint at sub packages, or might give you an idea how packages might be misnamed, if the parent package misses a package-info.
Additionally, it includes classes that do not have obfuscated names.

I can basically generate this for any version (You may need to do manual edits when the beginning of a package shifts to a different class. It adjusts automatically when either the mapped class name or the obfuscated name changes). I am going to make the generator open source, once it's a bit more polished.

The current stdout is as follows:
```
Package with no package-info: net.minecraft.realms
Package with no package-info: net.minecraft.server
Package with no package-info: net.minecraft.world.container
Package with no package-info: net.minecraft.world.level.block
Package with no package-info: com.mojang.blaze3d
Package with no package-info: com.mojang.blaze3d.audio
Package with no package-info: com.mojang.blaze3d.font
Package with no package-info: com.mojang.blaze3d.?
Package with no package-info: com.mojang.blaze3d.platform
Package with no package-info: com.mojang.blaze3d.shader
Package with no package-info: com.mojang.blaze3d.util
Package with no package-info: net.minecraft.client
Package with no package-info: net.minecraft.client.model
Package with no package-info: net.minecraft.client.tutorial
```

(`net.minecraft.client.tutorial` is at the very end, so there is most likely a package-info called `dyk`, but the tool can't really detect that)

**Comment by reoseah** [comment]
>I have written it in comments of that gist, but it's probably got lost at the end of that insanely sized file

in `net.minecraft.world.level.noise` package, there's actually at least 3 packages
```
net.minecraft.world.level.noise
    // here are main types that make up this system
    net/minecraft/world/biome/layer/LayerSampler (clk) 
    net/minecraft/world/biome/layer/LayerFactory (cll)  
    net/minecraft/world/biome/layer/CachingLayerSampler (clm)
    net/minecraft/world/biome/layer/LayerSampleContext (clo)
    net/minecraft/world/biome/layer/LayerRandomnessSource (clp)
    net/minecraft/world/biome/layer/CachingLayerContext (clq)
    // here are singleton implementations and BiomeLayers that assembles everything together
    net/minecraft/world/biome/layer/AddDeepOceanLayer (cls)
    net/minecraft/world/biome/layer/AddClimateLayers (clt)
    net/minecraft/world/biome/layer/IncreaseEdgeCurvatureLayer (clu)
    net/minecraft/world/biome/layer/AddMushroomIslandLayer (clv)
    net/minecraft/world/biome/layer/AddColdClimatesLayer (clw)
    net/minecraft/world/biome/layer/EaseBiomeEdgeLayer (clx)
    net/minecraft/world/biome/layer/SetBaseBiomesLayer (cly)
    net/minecraft/world/biome/layer/ContinentLayer (clz)
    net/minecraft/world/biome/layer/BiomeLayerSampler (cma)
    net/minecraft/world/biome/layer/BiomeLayers (cmb)
    net/minecraft/world/biome/layer/OceanTemperatureLayer (cmc)
    net/minecraft/world/biome/layer/ApplyOceanTemperatureLayer (cmd)
    net/minecraft/world/biome/layer/AddBambooJungleLayer (cme)
    net/minecraft/world/biome/layer/AddSunflowerPlainsLayer (cmf)
    net/minecraft/world/biome/layer/AddHillsLayer (cmg)
    net/minecraft/world/biome/layer/AddIslandLayer (cmh)
    net/minecraft/world/biome/layer/SimpleLandNoiseLayer (cmi)
    net/minecraft/world/biome/layer/NoiseToRiverLayer (cmj)
    net/minecraft/world/biome/layer/AddRiversLayer (cmk)
    net/minecraft/world/biome/layer/AddEdgeBiomesLayer (cml)
    net/minecraft/world/biome/layer/SmoothenShorelineLayer (cmm)
    net/minecraft/world/biome/layer/CellScaleLayer (cmn)
    net/minecraft/world/biome/layer/ScaleLayer (cmo)
    // here are all interfaces
    net/minecraft/world/biome/layer/InitLayer (cmq)
    net/minecraft/world/biome/layer/ParentedLayer (cmr)
    net/minecraft/world/biome/layer/MergingLayer (cms)
    net/minecraft/world/biome/layer/DiagonalCrossSamplingLayer (cmt)
    net/minecraft/world/biome/layer/IdentitySamplingLayer (cmu)
    net/minecraft/world/biome/layer/SouthEastSamplingLayer (cmv)
    net/minecraft/world/biome/layer/CrossSamplingLayer (cmw)
    net/minecraft/world/biome/layer/IdentityCoordinateTransformer (cmx)
    net/minecraft/world/biome/layer/NorthWestCoordinateTransformer (cmy)
    net/minecraft/world/biome/layer/CoordinateTransformer (cmz)
    net/minecraft/world/biome/layer/LayerOperator (cna)
```

Also probably Mojang names don't start with `Add` or `Apply`
`Scale` at the end of package is probably `Zoom`, `EdgeBiomes` is `TransitionBiomes`
Ocean and river related layers are close to each other, probably something like `OceanTemperatureLayer` and `OceanTemperatureMerger`

**Comment by liach** [comment]
Let's avoid the mojang map arr legal problem given [even MCP is trying to avoid it](https://cpw.github.io/MinecraftMappingData#the-legal-problem). There was 19w36a and there was drama.

**Comment by Runemoro** [comment]
@liach This isn't based on the Mojang maps, just on the code (look at the date of the gist). We need to match their package structure (not necessarily names), to avoid having package conflicts.

**Comment by liach** [comment]
imo checking with the package visibility index from enigma is sufficient. we have that check for our ci on yarn.

**Comment by Runemoro** [comment]
The package visibility index isn't sufficient. It doesn't cover future changes. The whole point of matching the Mojang package structure is so that in the future, if Mojang adds package-private members, we don't have to merge packages, causing confusion.

Also, the gist gives us information about which classes are possibly named wrong, and can also help us organize stuff better.

In any case, there is no legal problem here, this is based on vanilla code, like the rest of Yarn.

So I don't see why you closed this issue. You may disagree with it, but three others, [including asie](https://github.com/FabricMC/yarn/issues/673#issuecomment-502341884), agree that moving towards this structure is better.

**Comment by liach** [comment]
doesn't all unmapped classes go to net.minecraft package by default? and note that loader automatically fixes package private access issues when running in named mapping namespace

**Comment by Runemoro** [comment]
> doesn't all unmapped classes go to net.minecraft package by default

Yes, but if we have two classes in the same Mojang package, but two different Yarn packages, Mojang can add a package-private access between them, forcing us to merge them in the next snapshot.

**Comment by liach** [comment]
Feel free to keep track of this then. Should this issue stay open as a long-term project?

**Comment by liach** [comment]
In #2057 we now decide that we will require execution of yarn-mapped code to go through loader, which handles package access problems. This is now obsolete as package access is no longer of concern in that case.
