### ISSUE TITLE
Questions on some names

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#66]
Some of the names of classes might be modified. Ex. `TileEntity` -> `BlockEntity`, `Minecraft` -> `MinecraftClient`. Those classes have a more accurate name but they were not renamed because in other decompiling projects people were too lazy to change those common-used names.

**Comment by copygirl** [comment]
Not quite sure what this issue is for specifically. I think we specifically try to avoid using other mapping's names, but in some cases the name stuck, causing the community to adopt it. I'd love to have a place to point out possible name changes of important classes and discuss them.

Regarding the naming of blocks / tile entities, there's also the alternative of renaming `Block` -> `Tile`, which seems to be Mojang's convention of calling blocks. (Though I myself would prefer moving to `BlockEntity`.)

And regarding `MinecraftClient`, I'm not sure if that's appropriate. Perhaps something along the lines of `Game` or `App` might me more fitting?

**Comment by asiekierka** [comment]
According to MinecraftWiki at least, the TileEntities are now internally indeed called BlockEntities, which might make the TileEntity->BlockEntity rename a good idea. http://minecraft.gamepedia.com/Block_entity

MinecraftServer is already a thing, but MinecraftClient also handles the integrated server... MinecraftGame?

**Comment by darkevilmac** [comment]
I think MinecraftClient makes more sense as it matches with the naming of
the MinecraftServer class.

**Comment by liach** [comment]
@darkevilmac Yeah you are the one who suggested that name change in mcp but was rejected by the bad tempered guy.

**Comment by darkevilmac** [comment]
Yup, almost forgot I had suggested that until now.

**Comment by asiekierka** [comment]
@darkevilmac That would only make sense if Client and Server were opposites, but Client has its own Server...

**Comment by darkevilmac** [comment]
@asiekierka I don't think it's unheard of to have a game client with an integrated server. If it was running the server and the client all by itself I'd understand but as it is now there's still some separation there.

As a side note, from the issue I had initially made on MCP the official Mojang name is known to be Minecraft. Considering they're such important classes it might make sense to leave them as is.

**Comment by liach** [comment]
Ok. We still may actually use `BlockEntity` though.

**Comment by copygirl** [comment]
The following renaming has been done:
`TileEntity` => `BlockEntity` (#76)
`Minecraft` => `MinecraftGame` (#82)

**Comment by Prospector** [comment]
Ok well this has been done for 2 years. Close?

**Comment by liach** [comment]
Sorry, I should have closed this.
