### ISSUE TITLE
Include automatically mapped names in the .tiny files

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#718]
I suggest including names that are automatically mapped by stitch based on strings in the .tiny files generated by yarn. This would have three advantages:

 1. They should be accessible by mods at runtime, allowing mod developers to make things like reflection helpers that work with debofuscated names, and better crash report remappers (some java exception messages include field names)
 2. The .tiny files would be self-contained: no extra tools would be required to get them to their final form, making development of tools such as statistics generator easier, and making the .tiny files directly usable by a remapper.
 3. It just doesn't make sense to split them. The way I see it, the automatically generated names are a helpful feature to avoid having to manually map and update these names. Why have a distinction between manually mapped names and automatically mapped names?

**Comment by modmuss50** [comment]
> They should be accessible by mods at runtime

no, mods should use intermediary at all times, in dev or in prod. Do not expect to have yarn names (see bellow)

There is currently an issue open on the loom tracker as these field names are not included in the dev classpath.

> and better crash report remappers
Yes, this is the only reason I can see it being needed.

> no extra tools would be required

There a a yarn PR that needs finishing that adds a task to generate them, not perfect but could help make it easier for them to be used in full.

> It just doesn't make sense to split them

I think there are a few reasons behind this (@asiekierka will be able to confirm):

- Smaller file size

- They are technically not under the yarn license, bit of a grey area. (We do include debof names right now, so this only 1/2 a reason.)

We also plan to no longer use yarn names at runtime, and only have the intermediary names available, so that would make adding them to production pointless once this has been done.

**Comment by Runemoro** [comment]
> Smaller file size

Is it that much once it's compressed and you subtract the bandwidth saved by removing the name generating code from loom?

**Comment by liach** [comment]
i've already done that in my resource mapping pr but was called by modmuss to be revoked for the same reason

**Comment by Runemoro** [comment]
Doing this would also fix K9's !yf command not including auto-mapped fields.

**Comment by liach** [comment]
well, these auto names are no longer in yarn. we need to make sure of their license before we include them in tiny files.

**Comment by liach** [comment]
So this is still a license issue. Let @modmuss50 have the final voice.

**Comment by Runemoro** [comment]
Apparently v2 now includes these.
