### ISSUE TITLE
Minecart moving sound names messed up

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#918]
net/minecraft/client/sound/MinecartSoundInstance (class_1107) and net/minecraft/client/sound/RidingMinecartSoundInstance (class_1108) are mismatched. 1107 is actually the sound when player is riding, and 1108 is the ambient minecart sound.

Confirmed in both 1.14.4 and 19w42a.

**Comment by YanisBft** [comment]
Can't reproduce, classes seem named correctly

**Comment by liach** [comment]
look at the usage. one is played when a minecart is spawned in the world.

**Comment by YanisBft** [comment]
The issue comes from Mojang then, the sounds have wrong IDs

**Comment by liach** [comment]
this is sound instance class not sound events

**Comment by liach** [comment]
where do you find the ids? mind link?

**Comment by YanisBft** [comment]
When they call the super class in their constructor, the currently called `MinecartSoundInstance` and `RidingMinecartSoundInstance` classes respectively use `SoundEvents.ENTITY_MINECART_INSIDE` and `SoundEvents.ENTITY_MINECART_RIDING`. Those sound events are deobfuscated Mojang names, and refer to hardcoded IDs anyway.
That's why I don't get the issue here. Either it's a Mojang issue, either we don't understand what they mean by "riding" or "inside".

**Comment by liach** [comment]
one is ridden sound and one is ambient sound. don't trust thonkjang after all!
