### ISSUE TITLE
BufferBuilder -> ByteBufferVertexBuffer

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#929]
While Mojang calls (or called) it a `BufferBuilder` (see https://github.com/FabricMC/yarn/issues/313, which renamed it from `VertexBuffer` to `BufferBuilder`), the name `VertexBuffer` is much better.

 1. `BufferBuilder` is ambiguous. What sort of buffer is it building?
 2. `BufferBuilder` makes it seem like it's meant to build a buffer and then convert it to a regular buffer afterwards (like `StringBuilder`), but in fact it has all the regular methods of Java buffers (set position, get data, get/restore state), and it's used to pass around the vertex data, not just to build the buffer. Even Mojang calls it a "buffer" in log messages: `"Allocated only {}/{} buffers"`
 3. Calling it a "buffer" would shorten names like `BlockLayeredBufferBuilderStorage`, while making them less misleading.

**Comment by liach** [comment]
I support Runemoro. This buffer builder is just an intermediate buffer that makes sure the vertex buffers are properly formatted and tweaks certain input values based on its settings. However, given there may be a major snapshot this Wednesday, I suggest we revisit this topic after Wednesday snapshot is out.

**Comment by Player3324** [comment]
BufferBuilder may not be sufficiently descriptive since there are indeed multiple kinds of buffers, particularly in OpenGL, like vertex buffers, pixel store buffers, element index buffers and more.

The term VertexBuffer is much worse though, it can (and should) be easily understood as the Java side representation of the OpenGL VBO, holding the buffer object id etc. The "Object" suffix doesn't matter, it doesn't change the meaning and the GL methods operating on VBOs don't use it.

Buffer builder is an utility that assembles vertex data using something close to a standard builder pattern. It buffers the data internally like StringBuilder, but the main property+purpose is the building part - not the buffering. The buffering aspect is just a practical implementation requirement/choice. The class wouldn't change much if the output was pass-through instead of buffered.

BufferBuilder can and is being used with glDrawArrays without ever touching any OpenGL buffer object.

**Comment by Runemoro** [comment]
After talking with Player on Discord, I think we should `ByteBufferVertexBuffer` would be a better name for this class.

 1. It matches the log messages and debug renderer strings, which call them "buffers"
 2. It still works with the building part. A `ByteBuffer` builds byte data byte-by-byte, a `StringBuffer` builds strings, and a `PacketBuffer` builds packets, etc.
 3. The name makes it clear that it's a `ByteBuffer`-backed equivalent of `GlVertexBuffer`* which stores vertex data until it's copied into the GL buffer.
 4. While the name is long, almost all usages were replaced with `VertexConsumer` (which has all the methods of `BufferBuilder` except those for getting the data). All the rendering methods now receive `VertexConsumer`s, and the `ByteBufferVertexBuffer` is only used in a few places like the chunk renderer.

*currently called `GlBuffer`, but should be renamed to `GlVertexBuffer` since it's not any kind of GL buffer (it has a `VertexFormat` field).
