### ISSUE TITLE
BlockRenderManager.renderOnEntity -> renderBlock

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#939]
This method just renders a floating block (not at any world position). It's the same as the block render method, but doesn't accept a position parameter and instead renders it at the current position.

It's used by entities such as the minecart entity to render the block they're holding, but there's nothing that prevents this method from being used to render something else.

**Comment by liach** [comment]
They have dedicated render layers aside from their regular block counterparts. See `RenderLayers.getEntityBlockLayer`.

**Comment by Runemoro** [comment]
They're rendered on the entity layers because they act like entities, but there's no reason a mod couldn't use this for rendering something else.

**Comment by Runemoro** [comment]
For example, the skull, banner, bell, and many other things that are not entities use the "entity" layers.

**Comment by liach** [comment]
well, if a mod calls the method to render a regular block instead of one that renders a "block on entity", it will suffer from weird issues like lighting etc. see https://bugs.mojang.com/browse/MC-161891 and some of the [bug fixes in 19w42a](https://minecraft.gamepedia.com/Java_Edition_19w42a#Fixes). Hence a distinction should be made.

**Comment by liach** [comment]
Now we are using `renderBlockAsEntity`, which is a nice name in my opinion.
