### ISSUE TITLE
Entity vehicle variable.

### ISSUE THREAD

**Issue by darkevilmac** [asiekierka/MinecraftPOMF#94]
The current name for what a user is currently riding in the Entity class is vehicle, I don't think this really makes much sense, I've never really heard anyone refer to things like horses or pigs as vehicles. I can make a PR for ridingEntity, mountedEntity, or something along those lines if anyone agrees.

**Comment by copygirl** [comment]
As [mentioned in the PR](https://github.com/FabricMC/pomf/pull/96#discussion_r80952013), I'd prefer a different name for entities "riding" other entities. There's been `vehicle`, `ride`, `mount`, but what about `attach`? (By the way, that's by preference from least to most favorite.)

Anyone else have a suggestion?

**Comment by darkevilmac** [comment]
Attach doesn't really make sense for most scenarios. Again consider the
context, you don't attach yourself to a boat, a pig, or a minecart. You
don't mount the boat or minecart but you do mount a pig. You can also start
riding a pig though, and that matches most major use cases.

**Comment by copygirl** [comment]
You do attach yourself to the boat, because now you're moving as the boat is moving. It makes the most sense, at least programmatically, in my opinion.

**Comment by darkevilmac** [comment]
Attach doesn't seem very intuitive to me, as a side note Minecraft throws
exceptions for add passenger telling the user to call start riding.
Changing them to other things has the potential to cause confusion.

**Comment by copygirl** [comment]
Doesn't matter what Mojang calls it if we can name things better.

Attachments exist in other games as well, usually in the form of attaching things to body parts, connecting properties such as position and rotation. Attaching a player to a boat, minecart, horse or chair for example seems perfectly reasonable to me.

Riding may also be confusing due to the "is it riding or being ridden"? `startRiding` could very well mean "make the specified entity start riding this entity", where for example `attachTo` is very clear: `player.attachTo(boat)`.

**Comment by darkevilmac** [comment]
What is confusing about player.startRiding or player.stopRiding. That seems
pretty clear to me.

In regards to Mojang naming its relevant in this case because the method
explicitly tells you to call another if you did something wrong. Giving it
another name entirely is going to cause confusion.

**Comment by copygirl** [comment]
Does this mean we should take into account other error messages and crash reports too?

**Comment by darkevilmac** [comment]
If it was up to me I'd say yes but that's not the case. Unless we can start
remapping the messages in exceptions it makes sense to me at least to have
exceptions be accurate to the method name.

**Comment by copygirl** [comment]
Okay, I'll drop my resistance to your PR then, though I'd be interested to hear everyone else's opinions, still.

**Comment by mezz** [comment]
I like `mount`ing things most, and `riding` next. You never `attach` to the side or bottom, in Minecraft you're always hopping on top of something. 

Edit: actually riding makes more sense because while you can `ride` a pig and `ride` in a minecart, you don't really `mount` a minecart.

**Comment by copygirl** [comment]
@mezz Would you `ride` a seat or other stationary entity though, for example?

I'll speak out in favor of `mount`. It's a generic "get onto something" to me, common in games, clear in regards to `getMountedEntity` vs `getMountingEntity`, we can have `mount` and `unmount` (instead of `start/stopSomething`.

**Comment by modmuss50** [comment]
I agree with mezz, as riding fits in with all cases.

**Comment by mezz** [comment]
I think the only cases you would awkwardly `ride` a stationary thing is in modded, like bibliocraft chairs. All the other things I can think of move.

I do like `mount` and `unmount` because they are a simple pair of operations that are common in computers. "unmount" is a weird computers-word, the normal English word is "dismount". We don't have something similar for `ride` like `unride`. We could still use `startRiding` and `stopRiding`, but I like the mounted versions better than `getRidingEntity` and `getRiddenEntity`. Hm.

**Comment by Prospector** [comment]
I like mount and dismount personally
